### ISSUE TITLE
[android] Most site unavailable (SSL handshake failure)

### ISSUE THREAD

**Issue by odrevet** [odrevet/youtube-dl-kivy#1]
When using the android version, youtube works but other web sites don't. 

The Error returned is: 

ERROR: Unable to download JSON metadata: <urlopen error [Errno 1] _ssl.c:503: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:503: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))

As far as I known this is a Kivy / Buildozer issu as the Python version used to package android is 2.7.2 and is not compatible with current SSL.

**Comment by lelapin123** [comment]
Hello,

i added this code successfully in another project to remove this error
(still py2)

`
import os
#import ssl
import certifi

os.environ['SSL_CERT_FILE'] = certifi.where()
`

and i add this in buildozer.spec

openssl, certifi, pyopenssl

i am not sure that pyopenssl is useful, but i think i also needed it for something else.

**Comment by odrevet** [comment]
Thank you I will definitely try that

**Comment by odrevet** [comment]
With current version of kivy SSL is working out of the box. Tested by downloading video from Twitter,  niconico and sky news. 
Some site do not works for reasons unrelated either SSL handshake
