### ISSUE TITLE
Python 3 and android

### ISSUE THREAD

**Issue by lelapin123** [odrevet/youtube-dl-kivy#5]
As you probably know, python2 is more or less discontinued.
I would like to know if someone compiled successfully this project on python 3.

I compiled it successfully, but it seems that the part with youtube_dl doesn't work.

I don't want to open another topic for that, but it seems that i have this bug that is referenced in the source code:

"exception 'str' object has no attribute 'write'"

I get also this bug if i try to use the function:

.extract_info(video, download=False)
of youtube-dl;

Correct me if i am wrong, even though there is an exception handler in the source code, it seems that this "#ignore exception 'str' object has no attribute 'write'" bug, prevent the function to work and i can't figure out how to solve the problem...

**Comment by lelapin123** [comment]
Another issue: the default path to download is not reachable if i compile on python3 but it's not a big deal.

**Comment by odrevet** [comment]
with latest version of kivy python 3 is the default. 
the output directory has been updated
